window.tierData = [
  {
    tier: "S",
    title: "S Тир",
    heroes: [
      { name: "Король воргенов Генн", popularity: "89.3%", averagePlace: "3.72", image: "./heroes_bg/Genn, Worgen King.png" },
    ],
  },
  {
    tier: "A",
    title: "A Тир",
    heroes: [
      { name: "Миллифисент Манашторм", popularity: "33.2%", averagePlace: "3.83", image: "./heroes_bg/Millificent Manastorm.png" },
      { name: "Ченваала", popularity: "46.9%", averagePlace: "3.88", image: "./heroes_bg/Chenvaala.png" },
      { name: "Смертокрыл", popularity: "9.0%", averagePlace: "3.90", image: "./heroes_bg/Deathwing.png" },
      { name: "Король-лич", popularity: "50.0%", averagePlace: "3.92", image: "./heroes_bg/The Lich King.png" },
      { name: "Воевода Саурфанг", popularity: "20.4%", averagePlace: "3.98", image: "./heroes_bg/Overlord Saurfang.png" },
      { name: "Раканишу", popularity: "17.9%", averagePlace: "4.00", image: "./heroes_bg/Rakanishu.png" },
      { name: "Морхи", popularity: "65.4%", averagePlace: "4.02", image: "./heroes_bg/Morchie.png" },
      { name: "Ониксия", popularity: "27.9%", averagePlace: "4.02", image: "./heroes_bg/Onyxia.png" },
      { name: "Королева Пыхлевых", popularity: "16.9%", averagePlace: "4.02", image: "./heroes_bg/Queen Wagtoggle.png" },
      { name: "Мурозонд Освобожденный", popularity: "61.1%", averagePlace: "4.03", image: "./heroes_bg/Murozond, Unbounded.png" },
      { name: "Кнопка", popularity: "63.6%", averagePlace: "4.04", image: "./heroes_bg/Buttons.png" },
      { name: "Терон Кровожад", popularity: "55.9%", averagePlace: "4.05", image: "./heroes_bg/Teron Gorefiend.png" },
      { name: "Торим, владыка бури", popularity: "58.3%", averagePlace: "4.06", image: "./heroes_bg/Thorim, Stormlord.png" },
      { name: "Джим Рейнор", popularity: "22.8%", averagePlace: "4.06", image: "./heroes_bg/Jim Raynor.png" },
      { name: "Ахалаймахалай", popularity: "26.5%", averagePlace: "4.06", image: "./heroes_bg/The Great Akazamzarak.png" },
      { name: "Снид", popularity: "17.4%", averagePlace: "4.07", image: "./heroes_bg/Sneed.png" },
      { name: "Экзарх Отаар", popularity: "15.5%", averagePlace: "4.07", image: "./heroes_bg/Exarch Othaar.png" },
      { name: "Н'Зот", popularity: "35.3%", averagePlace: "4.09", image: "./heroes_bg/N'Zoth.png" },
      { name: "Леди Вайш", popularity: "24.4%", averagePlace: "4.10", image: "./heroes_bg/Lady Vashj.png" },
      { name: "Сильвана Ветрокрылая", popularity: "56.9%", averagePlace: "4.10", image: "./heroes_bg/Sylvanas Windrunner.png" },
      { name: "Дрыжеглот", popularity: "48.0%", averagePlace: "4.12", image: "./heroes_bg/Shudderwock.png" },
      { name: "Король Мукла", popularity: "9.9%", averagePlace: "4.13", image: "./heroes_bg/King Mukla.png" },
      { name: "Лоскутик", popularity: "32.4%", averagePlace: "4.13", image: "./heroes_bg/Patchwerk.png" },
      { name: "Сэр Финли Мрргглтон", popularity: "47.0%", averagePlace: "4.14", image: "./heroes_bg/Sir Finley Mrrgglton.png" },
      { name: "Королева Азшара", popularity: "33.1%", averagePlace: "4.15", image: "./heroes_bg/Queen Azshara.png" },
      { name: "Ини Штормоверь", popularity: "28.1%", averagePlace: "4.16", image: "./heroes_bg/Ini Stormcoil.png" },
    ],
  },
  {
    tier: "B",
    title: "B Тир",
    heroes: [
      { name: "Капитан Юдора", popularity: "35.7%", averagePlace: "4.17", image: "./heroes_bg/Captain Eudora.png" },
      { name: "Грибомант Флургл", popularity: "29.3%", averagePlace: "4.17", image: "./heroes_bg/Fungalmancer Flurgl.png" },
      { name: "Мурлок Холмс", popularity: "26.4%", averagePlace: "4.18", image: "./heroes_bg/Murloc Holmes.png" },
      { name: "Укротитель ящеров Бранн", popularity: "59.2%", averagePlace: "4.18", image: "./heroes_bg/Dinotamer Brann.png" },
      { name: "Ал'акир", popularity: "26.8%", averagePlace: "4.18", image: "./heroes_bg/Al'Akir.png" },
      { name: "Менеджер Марин", popularity: "69.2%", averagePlace: "4.18", image: "./heroes_bg/Marin the Manager.png" },
      { name: "Йогг-Сарон", popularity: "30.4%", averagePlace: "4.19", image: "./heroes_bg/Yogg-Saron, Hope's End.png" },
      { name: "Ванндар Грозовая Вершина", popularity: "34.2%", averagePlace: "4.20", image: "./heroes_bg/Vanndar Stormpike.png" },
      { name: "Мутанус Пожиратель", popularity: "30.5%", averagePlace: "4.20", image: "./heroes_bg/Mutanus the Devourer.png" },
      { name: "Танцор Дэрил", popularity: "20.3%", averagePlace: "4.21", image: "./heroes_bg/Dancin' Deryl.png" },
      { name: "Дрек'Тар", popularity: "32.3%", averagePlace: "4.21", image: "./heroes_bg/Drek'Thar.png" },
      { name: "Маиев Песнь Теней", popularity: "17.1%", averagePlace: "4.22", image: "./heroes_bg/Maiev Shadowsong.png" },
      { name: "Предсказатель Нобундо", popularity: "28.0%", averagePlace: "4.22", image: "./heroes_bg/Farseer Nobundo.png" },
      { name: "Вол'джин", popularity: "12.6%", averagePlace: "4.22", image: "./heroes_bg/Vol'jin.png" },
      { name: "Билетекус", popularity: "32.5%", averagePlace: "4.23", image: "./heroes_bg/Tickatus.png" },
      { name: "А. Ф. Ка", popularity: "51.2%", averagePlace: "4.24", image: "./heroes_bg/A. F. Kay.png" },
      { name: "Посол Фаэлин", popularity: "53.3%", averagePlace: "4.24", image: "./heroes_bg/Ambassador Faelin.png" },
      { name: "Доктор Гуляка", popularity: "19.8%", averagePlace: "4.24", image: "./heroes_bg/Doctor Holli'dae.png" },
      { name: "Инге Стальной Гимн", popularity: "10.4%", averagePlace: "4.25", image: "./heroes_bg/Inge, the Iron Hymn.png" },
      { name: "Музыкальный менеджер Е.Т.С.", popularity: "43.9%", averagePlace: "4.25", image: "./heroes_bg/E.T.C., Band Manager.png" },
      { name: "Миллхаус Манашторм", popularity: "13.7%", averagePlace: "4.25", image: "./heroes_bg/Millhouse Manastorm.png" },
      { name: "И'Шарадж", popularity: "21.3%", averagePlace: "4.25", image: "./heroes_bg/Y'Shaarj.png" },
      { name: "Сайлас Новолуний", popularity: "28.8%", averagePlace: "4.25", image: "./heroes_bg/Silas Darkmoon.png" },
      { name: "Элиза Звездочет", popularity: "19.8%", averagePlace: "4.25", image: "./heroes_bg/Elise Starseeker.png" },
      { name: "Мастер Нгуен", popularity: "55.6%", averagePlace: "4.26", image: "./heroes_bg/Master Nguyen.png" },
      { name: "Рокара", popularity: "10.4%", averagePlace: "4.26", image: "./heroes_bg/Rokara.png" },
      { name: "Крысиный король", popularity: "25.4%", averagePlace: "4.28", image: "./heroes_bg/The Rat King.png" },
      { name: "Пират Глазастик", popularity: "34.3%", averagePlace: "4.28", image: "./heroes_bg/Patches the Pirate.png" },
      { name: "Галакронд", popularity: "41.3%", averagePlace: "4.28", image: "./heroes_bg/Galakrond.png" },
      { name: "Артанис", popularity: "19.0%", averagePlace: "4.29", image: "./heroes_bg/Artanis.png" },
      { name: "Варден Луч Рассвета", popularity: "31.9%", averagePlace: "4.29", image: "./heroes_bg/Varden Dawngrasp.png" },
      { name: "Механо-усилитель", popularity: "20.2%", averagePlace: "4.29", image: "./heroes_bg/Enhance-o Mechano.png" },
      { name: "Джордж Падший", popularity: "20.2%", averagePlace: "4.29", image: "./heroes_bg/George the Fallen.png" },
    ],
  },
  {
    tier: "C",
    title: "C Тир",
    heroes: [
      { name: "Король воров Вихлепых", popularity: "23.4%", averagePlace: "4.31", image: "./heroes_bg/Heistbaron Togwaggle.png" },
      { name: "Сир Денатрий", popularity: "75.9%", averagePlace: "4.32", image: "./heroes_bg/Sire Denathrius.png" },
      { name: "Тамсин Роум", popularity: "15.1%", averagePlace: "4.33", image: "./heroes_bg/Tamsin Roame.png" },
      { name: "Озумат", popularity: "11.7%", averagePlace: "4.33", image: "./heroes_bg/Ozumat.png" },
      { name: "Кариэль Роум", popularity: "6.1%", averagePlace: "4.33", image: "./heroes_bg/Cariel Roame.png" },
      { name: "Принц Кель'тас", popularity: "17.7%", averagePlace: "4.34", image: "./heroes_bg/Kael'thas Sunstrider.png" },
      { name: "Ло, живая легенда", popularity: "33.0%", averagePlace: "4.35", image: "./heroes_bg/Loh, the Living Legend.png" },
      { name: "Тюремщик", popularity: "10.1%", averagePlace: "4.35", image: "./heroes_bg/The Jailer.png" },
      { name: "Эдвин ван Клифф", popularity: "10.1%", averagePlace: "4.36", image: "./heroes_bg/Edwin VanCleef.png" },
      { name: "Бру'кан", popularity: "12.2%", averagePlace: "4.37", image: "./heroes_bg/Bru'kan.png" },
      { name: "Капитан Др-р-р-робитель", popularity: "47.9%", averagePlace: "4.37", image: "./heroes_bg/Cap'n Hoggarr.png" },
      { name: "Мистер Бигглсуорт", popularity: "21.8%", averagePlace: "4.37", image: "./heroes_bg/Mr. Bigglesworth.png" },
      { name: "Лорд Джараксус", popularity: "37.1%", averagePlace: "4.37", image: "./heroes_bg/Lord Jaraxxus.png" },
      { name: "Крагг Поднебесный", popularity: "20.9%", averagePlace: "4.37", image: "./heroes_bg/Skycap'n Kragg.png" },
      { name: "Клонист Зерек", popularity: "43.5%", averagePlace: "4.37", image: "./heroes_bg/Zerek, Master Cloner.png" },
      { name: "К'Тун", popularity: "9.7%", averagePlace: "4.38", image: "./heroes_bg/C'Thun.png" },
      { name: "Малигос", popularity: "20.9%", averagePlace: "4.38", image: "./heroes_bg/Malygos.png" },
      { name: "Рок-мастер Вун", popularity: "36.2%", averagePlace: "4.39", image: "./heroes_bg/Rock Master Voone.png" },
      { name: "Лесной властелин Кенарий", popularity: "47.1%", averagePlace: "4.39", image: "./heroes_bg/Forest Lord Cenarius.png" },
      { name: "Аранна Звездочет", popularity: "26.7%", averagePlace: "4.40", image: "./heroes_bg/Aranna Starseeker.png" },
      { name: "Синдрагоса", popularity: "37.3%", averagePlace: "4.40", image: "./heroes_bg/Sindragosa.png" },
      { name: "Тавиш Грозовая Вершина", popularity: "23.3%", averagePlace: "4.41", image: "./heroes_bg/Tavish Stormpike.png" },
      { name: "Смотритель", popularity: "19.4%", averagePlace: "4.41", image: "./heroes_bg/The Curator.png" },
      { name: "Серокрон", popularity: "31.5%", averagePlace: "4.41", image: "./heroes_bg/Greybough.png" },
      { name: "Бурекрыл", popularity: "26.7%", averagePlace: "4.41", image: "./heroes_bg/Galewing.png" },
      { name: "Джандис Барова", popularity: "20.8%", averagePlace: "4.42", image: "./heroes_bg/Jandice Barov.png" },
      { name: "Кок Пирожок", popularity: "24.0%", averagePlace: "4.42", image: "./heroes_bg/Cookie the Cook.png" },
      { name: "Гафф Рунический Тотем", popularity: "36.9%", averagePlace: "4.42", image: "./heroes_bg/Guff Runetotem.png" },
      { name: "Суперзлодей Рафаам", popularity: "24.5%", averagePlace: "4.42", image: "./heroes_bg/Arch-Villain Rafaam.png" },
    ],
  },
  {
    tier: "D",
    title: "D Тир",
    heroes: [
      { name: "Иллидан", popularity: "27.6%", averagePlace: "4.45", image: "./heroes_bg/Illidan Stormrage.png" },
      { name: "Ноздорму", popularity: "23.6%", averagePlace: "4.45", image: "./heroes_bg/Nozdormu.png" },
      { name: "Рено Джексон", popularity: "47.6%", averagePlace: "4.46", image: "./heroes_bg/Reno Jackson.png" },
      { name: "Страж леса Ому", popularity: "35.9%", averagePlace: "4.48", image: "./heroes_bg/Forest Warden Omu.png" },
      { name: "Вечная Токи", popularity: "40.1%", averagePlace: "4.48", image: "./heroes_bg/Infinite Toki.png" },
      { name: "Зирелла", popularity: "27.5%", averagePlace: "4.48", image: "./heroes_bg/Xyrella.png" },
      { name: "Керриган, Королева Клинков", popularity: "9.4%", averagePlace: "4.49", image: "./heroes_bg/Kerrigan, Queen of Blades.png" },
      { name: "Принц Галливикс", popularity: "44.1%", averagePlace: "4.49", image: "./heroes_bg/Trade Prince Gallywix.png" },
      { name: "Рагнарос", popularity: "13.9%", averagePlace: "4.50", image: "./heroes_bg/Ragnaros the Firelord.png" },
      { name: "Капитан Кривоклык", popularity: "17.0%", averagePlace: "4.50", image: "./heroes_bg/Captain Hooktusk.png" },
      { name: "Лич Баз'хиал", popularity: "19.4%", averagePlace: "4.51", image: "./heroes_bg/Lich Baz'hial.png" },
      { name: "Куртрус Ливень Пепла", popularity: "24.1%", averagePlace: "4.51", image: "./heroes_bg/Kurtrus Ashfallen.png" },
      { name: "Скаббс Маслорез", popularity: "31.1%", averagePlace: "4.51", image: "./heroes_bg/Scabbs Cutterbutter.png" },
      { name: "Зефрис Великий", popularity: "33.1%", averagePlace: "4.52", image: "./heroes_bg/Zephrys, the Great.png" },
      { name: "Змеиные глазки", popularity: "44.9%", averagePlace: "4.54", image: "./heroes_bg/Snake eyes.png" },
      { name: "Вестник смерти Черношип", popularity: "15.5%", averagePlace: "4.57", image: "./heroes_bg/Death Speaker Blackthorn.png" },
      { name: "Искательница Хроми", popularity: "26.0%", averagePlace: "4.58", image: "./heroes_bg/Time Twister Chromie.png" },
      { name: "Пирамидон", popularity: "13.7%", averagePlace: "4.59", image: "./heroes_bg/Pyramad.png" },
      { name: "Тесс Седогрив", popularity: "44.5%", averagePlace: "4.60", image: "./heroes_bg/Tess Greymane.png" },
      { name: "Профессор Мерзоцид", popularity: "15.6%", averagePlace: "4.64", image: "./heroes_bg/Professor Putricide.png" },
      { name: "Алекстраза", popularity: "21.6%", averagePlace: "4.67", image: "./heroes_bg/Alexstrasza.png" },
      { name: "Господин Часовщик", popularity: "67.4%", averagePlace: "4.71", image: "./heroes_bg/Mister Clocksworth.png" },
      { name: "Тей'телан Кровавый Взор", popularity: "9.6%", averagePlace: "4.75", image: "./heroes_bg/Tae'thelan Bloodwatcher.png" },
      { name: "Изера", popularity: "21.7%", averagePlace: "4.85", image: "./heroes_bg/Ysera.png" },
    ],
  },
];;
